### PR TITLE
Include safe filenames for components

### PR DESCRIPTION
**Pull request by SvanBoxel**
Component names in Figma contain all sorts of characters which choke operating systems. For example; having a slash in one of your components will result in the following error

```
(node:72802) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'component / with / slash.jpg'
```

This converts component names into filenames which can be safely used (and includes those filenames in the data.json file)

### CODE REVIEW

**Comment by BinaryMuse** [comment]
Good call; this change seems reasonable, but I wonder if we should go ahead and do something more robust, e.g. https://github.com/parshap/node-sanitize-filename/blob/master/index.js

@jonrohan Are you still the best person to ping on this? Any thoughts?

**Comment by SvanBoxel** [comment]
Makes sense @BinaryMuse. Awaiting @jonrohan's feedback before I implement the library you suggested.

**Comment by jonrohan** [comment]
👍🏻 on using sanitize

**Comment by SvanBoxel** [comment]
Updates per your feedback @jonrohan  @BinaryMuse

**Comment by johnsBeharry** [comment]
is this ready to merge into master?

**Comment by SvanBoxel** [comment]
Development-wise I believe it's ready. Waiting for @jonrohan's review. 😄

**Comment by BinaryMuse** [comment]
Thanks for this PR! I'm going to merge and publish a new version, but the Primer organization no longer uses this action so we won't be maintaining it further. It is MIT licensed, so please feel free to fork it (or continue using the latest version, it'll just be archived).

**Comment by BinaryMuse** [comment]
This is now available in `v1.0.0-alpha.3`

**Pull request merged**
